# Generated by Django 5.2.16 on 2026-07-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helperprofile",
            name="intro",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="helperprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/%Y/%m/%d/"
            ),
        ),
    ]
