# Generated by Django 5.2.16 on 2026-07-14 04:45

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_helperprofile_intro_helperprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helperprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='helperprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='helperprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.profile_image_upload_to),
        ),
    ]
