# Generated by Django 5.2.16 on 2026-07-12 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_key', models.CharField(db_index=True, max_length=64)),
                ('reservation_step', models.CharField(blank=True, default='', max_length=50)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/%Y/%m/%d/')),
                ('canvas_data', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('WAITING', '대기 중 (broadcast 중)'), ('MATCHED', '도우미 매칭됨'), ('IN_PROGRESS', '도움 진행 중'), ('DONE', '완료 (효자뱃지 지급 대상)'), ('CANCELLED', "이용자가 '괜찮아요' 등으로 종료")], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
